
MPI_TYPE=MSMPI
XMSMPI_INC='$(subst \,/,$(MSMPI_INC))'
XMSMPI_LIB64='$(subst \,/,$(MSMPI_LIB64))'
TARGET_ARCH=64
MPILIBA=../libmsmpi64.a
PKG_CFLAGS= -I$(XMSMPI_INC) -DMSMPI_NO_DEPRECATE_20 -DWIN32
PKG_LIBS= $(MPILIBA) -L"$(R_HOME)/bin$(R_ARCH)" -lR

CP = cp
SOURCES_C=RhpcWorker.c RhpcWorker_LapplyLB.c RhpcWorker_Lapplyseq.c RhpcWorker_WorkerCall.c
OBJECTS=$(SOURCES_C:.c=.o)
COMMON_OBJECTS=../common/RhpcSerialize.o ../common/RhpcMS.o


all:	RhpcWorker$(TARGET_ARCH).exe fakemaster$(TARGET_ARCH).exe RhpcWin$(TARGET_ARCH).cmd Rhpc$(TARGET_ARCH).cmd RhpcSpawnWin$(TARGET_ARCH).cmd
	@echo $(CP) -p RhpcWorker$(TARGET_ARCH).exe $(R_PACKAGE_DIR)
	@$(CP) -p RhpcWorker$(TARGET_ARCH).exe $(R_PACKAGE_DIR)
	@echo $(CP) -p fakemaster$(TARGET_ARCH).exe $(R_PACKAGE_DIR)
	@$(CP) -p fakemaster$(TARGET_ARCH).exe $(R_PACKAGE_DIR)
	@$(CP) -p RhpcWin$(TARGET_ARCH).cmd $(R_PACKAGE_DIR)
	@$(CP) -p Rhpc$(TARGET_ARCH).cmd $(R_PACKAGE_DIR)
	@$(CP) -p RhpcSpawnWin$(TARGET_ARCH).cmd $(R_PACKAGE_DIR)

RhpcWin$(TARGET_ARCH).cmd: RhpcWin.cmd.in
	$(SED) -b -e 's/@@ARCH@@/$(TARGET_ARCH)/g' < RhpcWin.cmd.in > $@

Rhpc$(TARGET_ARCH).cmd: Rhpc.cmd.in
	$(SED) -b -e 's/@@ARCH@@/$(TARGET_ARCH)/g' < Rhpc.cmd.in > $@

RhpcSpawnWin$(TARGET_ARCH).cmd: RhpcSpawnWin.cmd.in
	$(SED) -b -e 's/@@ARCH@@/$(TARGET_ARCH)/g' < RhpcSpawnWin.cmd.in > $@

RhpcWorker$(TARGET_ARCH).exe: $(MPILIBA) $(OBJECTS) $(COMMON_OBJECTS)
	$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) $(OBJECTS) $(COMMON_OBJECTS) -o $@ $(PKG_LIBS) $(LIBR)

RhpcWorker.o: RhpcWorker.c
	$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) $(PKG_CFLAGS) -c $< -o $@

RhpcWorker_LapplyLB.o: RhpcWorker_LapplyLB.c
	$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) $(PKG_CFLAGS) -c $< -o $@

RhpcWorker_Lapplyseq.o: RhpcWorker_Lapplyseq.c
	$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) $(PKG_CFLAGS) -c $< -o $@

RhpcWorker_WorkerCall.o: RhpcWorker_WorkerCall.c
	$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) $(PKG_CFLAGS) -c $< -o $@

fakemaster$(TARGET_ARCH).exe: fakemaster$(TARGET_ARCH).o
	$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) $< -o $@

fakemaster$(TARGET_ARCH).o: fakemaster.c
	$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) -c $< -o $@

clean:
	@-$(RM) -f RhpcWorker RhpcWorker64.exe RhpcWin64.cmd RhpcSpawnWin64.cmd $(OBJECTS) fakemaster*.o fakemaster*.exe
